### ISSUE TITLE
PHP 8.0, 8.1

### ISSUE THREAD

**Issue by tacman** [kevinpapst/TablerBundle-Demo#1]
Wahoo, excited to see a demo for TablerBundle!

I think the demo should run with the latest tools (symfony 5.4 and Symfony 6, php 7.4, 8.0 and 8.1).  I'm getting conflicts with doctrine/common, for example, with PHP 8.

Happy to help test!

**Comment by kevinpapst** [comment]
WOW, that was a quick discovery. How did you do that? 😁 

I only tested with 7.4 yet. It works locally (even though a lot of the demo is broken by now).

Send in PRs if you find solutions for your issues please! I can use all the help available 👍

**Comment by tacman** [comment]
I was updating my own mess of an admin bundle, which currently using
AdminLTE, recently switched to using the excellent Umbrella framework
(which uses the free version of the AdminKit theme).

I wish Umbrella used Tabler instead, and his approach to the architecture
is pretty impressive.  Plus, it runs on the latest of everything (PHP 8.1,
Symfony 5.4 or 6).

So I revisited your TablerBundle because there are some things I quite
like.  At this point, 7.4 is only in security fixes, so while I understand
that TablerBundle should run PHP 7.4, I think the _demo_ should run using
the latest components, best practices, etc.

Even on 7.4 I'm not getting the demo to work, once I do I'll bump
everything to work on 7.4+

Neither the property "button" nor one of the methods "button()",
"getbutton()"/"isbutton()"/"hasbutton()" or "__call()" exist and have
public access in class "KevinPapst\TablerBundle\Helper\ContextHelper".

**Comment by kevinpapst** [comment]
Please do a `composer update` to fix the issue. I had fixed it locally in the theme and forgot to push. 

This demo is only here to showcase the theme usage. I do not want to rebuild a "Symfony best practices" app, the core team does that much better 😁 but if you want to update it to 8, please send PRs! Shouldn't be much of a difference though for the "demo aspect".

**Comment by kevinpapst** [comment]
Took me about a day to integrate it into my rather large time-tracker application and then many more hours to smooth out all the issues that were coming from the bootstrap 3 to 5 migration (which was actually the bigger problem than the bundle switch).

**Comment by kevinpapst** [comment]
I think it is necessary to sync all configs with the ones from a fresh Symfony 5 installation.
They are still mapped to SF4 code and a lot of deprecations are triggered.

**Comment by kevinpapst** [comment]
Can you retest PHP 8 and close if it now works?

**Comment by tacman** [comment]
Yep, works great!

What do you think about documenting the menu creation?  Both your menus and
knp_menu (which I hope you'll still support with this bundle!)

I'll try to write up a little "getting started" guide to include in the
documentation.

**Comment by kevinpapst** [comment]
I started documentation for the bundle (eg Menu):
https://github.com/kevinpapst/TablerBundle/blob/main/docs/index.md

KNP Menu is not yet only roadmap, but feel free to open a feature request in the bundle repo.

**Comment by kevinpapst** [comment]
And btw: the demo and the bundle are tested with PHP 7.5, 8.0 and 8.1. 
See Actions, eg here: https://github.com/kevinpapst/TablerBundle-Demo/actions/runs/1676882996
