### ISSUE TITLE
Code highlight

### ISSUE THREAD

**Issue by cavasinf** [kevinpapst/TablerBundle-Demo#15]
It can be nice to have syntax color when `code` are displayed.
Like [Symfony Demo](https://github.com/symfony/demo/blob/ecf3f8526c59ebe6cb68b2b79fac5251c9430607/package.json#L12) that use [highlight.js](https://highlightjs.org/)

![image](https://user-images.githubusercontent.com/25293190/189105516-fbe50761-33a7-438c-aed3-8ee17ee88ab0.png)

**Comment by kevinpapst** [comment]
Good idea, PRs are welcome 😁
