### ISSUE TITLE
Support for PHP 8.1

### ISSUE THREAD

**Issue by cavasinf** [kevinpapst/TablerBundle-Demo#19]
With Tabler update https://github.com/kevinpapst/TablerBundle/pull/123

I've reworked our docker-compose image:
- Newer node version
- PHP 8.1

But Demo only allows 8.0 build.
Can you @kevinpapst allows 8.1 and/or 8.0 ?

**Comment by kevinpapst** [comment]
Done in https://github.com/kevinpapst/TablerBundle-Demo/commit/dba0e16e17937d43e075191ab6d4b1b70f4292fb

**Comment by cavasinf** [comment]
Not checked, but this will be problematic no?
https://github.com/kevinpapst/TablerBundle-Demo/blob/dba0e16e17937d43e075191ab6d4b1b70f4292fb/composer.json#L37

**Comment by kevinpapst** [comment]
No. But you can easily try the difference.
