### ISSUE TITLE
How to configure for sidebar menu

### ISSUE THREAD

**Issue by tacman** [kevinpapst/TablerBundle-Demo#2]
Is there a setting for configuring the menu on the left, as a sidebar?

![image](https://user-images.githubusercontent.com/619585/146572007-030332c7-ea81-4f20-a148-cd6ceadd832c.png)

**Comment by kevinpapst** [comment]
See https://github.com/kevinpapst/TablerBundle/pull/3

Lets discuss everything that is related to the actual bundle in https://github.com/kevinpapst/TablerBundle

Only demo related stuff here, otherwise I completely loose track 😁

**Comment by kevinpapst** [comment]
Re-open, as we have to integrate a button to switch it in the demo...

**Comment by kevinpapst** [comment]
Merged a couple of minutes ago
